### ISSUE TITLE
OpenData Frontend: Editor de filtros geográficos

### ISSUE THREAD

**Issue by BenjiRS94** [som-labs/community#2]
## Título
*  Editor de filtro geográfico para el front end Opendata

## Contexto y necesidad
*  Opendata es una API que ofrece la evolucion de socias y contratos agregados y filtrados por localización geográfica. La API ofrece un [frontend](http://opendata.somenergia.coop) para facilitar el acceso sin programar pero **los filtros geográficos aun se tienen que escribir como una url query** tipo `ccaa=8&city=4343&city=4366`. No solo tienes que saber como escribirla sino que ademas tienes que averiguar los codigos que asigna el INE a las ciudades, provincias... que quieres filtrar.

## Objetivo
*  Añadir un componente a la interficie gráfica para que los usuarios puedan especificar de forma más sencilla el ambito geográfico a filtrar.

## Potenciales usuarios
*  Todas las socias de Som Energia, especialmente los grupos locales

**Comment by vokimon** [comment]
Fixed by
https://github.com/Som-Energia/opendata-ui/commit/fb6074bac570e407ae898939ba2858826585a118
