### ISSUE TITLE
OpenData Frontend: Visualización tipo Mapa

### ISSUE THREAD

**Issue by BenjiRS94** [som-labs/community#4]
## Resumen
*  Visualización de datos en forma de mapa para el front end Opendata

## Contexto y necesidad
*  Opendata es una API que ofrece la evolucion de socias y contratos agregados y filtrados por localización geográfica. La API ofrece un [frontend](http://opendata.somenergia.coop) para facilitar el acceso sin programar pero la presentacion del resultado aún es muy burda.
* Los mapas ofrecen una forma más visual de presentar los datos.

## Objetivo
*  Anadir un modo visualización en forma de mapa.

## Potenciales usuarios
*  Todas las personas socias de Som Energia, especialmente los grupos locales

**Comment by vokimon** [comment]
Esta seria la visualizacion que ha hecho Mar Jene para sus practicas de master. Cierro la tarea.
